[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "geopy>=2.4.1",
    "google-cloud-vision>=3.10.1",
    "openai>=1.76.0",
    "sift-stack-py>=0.5.1",
    "streamlit>=1.44.1",
]
